development:
  paypal_email: seller@damagecontrolfamily.com
  paypal_secret: foobar
  paypal_cert_id: DSUTZBZLUCCV8
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  
test:
  paypal_email: test@damagecontrolfamily.com
  paypal_secret: foobar
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl
  
production:
  paypal_email: seller@damagecontrolfamily.com
  paypal_secret: foobar
  paypal_cert_id: DSUTZBZLUCCV8
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
