development:
  adapter: postgresql
  database: damage
  host: localhost
  
test:
  adapter: postgresql
  database: damage
  host: localhost
  
production:
  adapter: postgresql
  database: damage
  host: localhost
  encoding: unicode
  pool: 5
  
